### ISSUE TITLE
Support fixed-header with HTML Tables

### ISSUE THREAD

**Issue by speige** [rintoj/ngx-virtual-scroller#237]
Feature request.

It can be done by commenting out this section of code from the getElementsOffset function:
```
if (this.containerElementRef && this.containerElementRef.nativeElement) {
	offset += this.containerElementRef.nativeElement[this._offsetType];
}
```
However, the math seems off because the header jumps around by a few pixels each time you scroll.

**Comment by vanackere** [comment]
Hi,

 I'm interested in implementing / fixing this feature. As a first try I commented the section of code you mentioned but after this the header appears at top position only during scrolling. Are there any other modification I should be doing to test this ?

**Comment by vanackere** [comment]
Thanks, it was indeed somewhat working but in my case the header was mostly hidden at the top (and I did not see it because it had not a different background color).
I'll experiment a bit more with this... Don't you think some additional css might be necessary to properly set the header in place ?

**Comment by vanackere** [comment]
How about doing this by computing/applying the right css rule on the header element while scrolling ? 
```
transform: translateY(90px);
```

Do you think it could work ?

**Comment by speige** [comment]
I agree that a CSS solution is better than a javascript+math solution, but I'm not sure it's possible.

One tricky thing I've noticed is that many css changes on the table related elements completely break the whole table functionality.

For example, this keeps the header on top, but breaks the column widths.
```
thead { position: fixed; top: 0; }
```
Normally position: fixed would go to the top of the page, but since .scrollable-content has a transform, the position: fixed is relative to .scrollable-content


I don't think the code change I mentioned related to getElementsOffset has any value. I think I just stumbled across that by accident & it strangely seemed to help, but I don't think it's the correct solution. Forget I ever mentioned it :)

I think your transform translateY is a good way to solve this! Here's some testing I did.

Look at the below 3 screenshots:

![image](https://user-images.githubusercontent.com/2002030/46495691-5ac9c680-c7d3-11e8-857a-442df946508f.png)
This shows that the header is 27px tall. This could be measured via javascript. It shouldn't change while scrolling, so it could be measured 1x & cached (unless the programmer makes the heeader dynamic, in which case we could give them a invalidateMeasurements API).


![image](https://user-images.githubusercontent.com/2002030/46495798-995f8100-c7d3-11e8-8562-9bdea2e5872b.png)
At this scroll position, the 1st row is almost completely scrolled out of view. If you measure the height of the blue highlight above the table border it's 37px. So, we can fix the header by using transform: translateY(64px) on the thead [header height + blue highlight height above border]
![image](https://user-images.githubusercontent.com/2002030/46495969-10951500-c7d4-11e8-8cea-5e1b4a1798ad.png)


Unfortunately, we probably have to use math to calculate this value, because the the amount of blue highlight scrolled above the table border will change depending on the scroll position.

Here's another example:
![image](https://user-images.githubusercontent.com/2002030/46496046-3de1c300-c7d4-11e8-9aea-3f3a51f19883.png)
The blue highlight above the table border is only 6px. If we add the same 27px header height, we get transform: translateY(33px) for the thead.
![image](https://user-images.githubusercontent.com/2002030/46496212-b5afed80-c7d4-11e8-8f1e-9b6e6cf8ff1e.png)


I think this could work. I think measuring the thead height via javsacript is easy. The question is, what javascript can we use to measure the blue highlight above the table border? Probably not too hard, but I don't know the formula off the top of my head.

Thoughts?

**Comment by vanackere** [comment]
Pull request here:

 https://github.com/rintoj/ngx-virtual-scroller/pull/250

**Comment by speige** [comment]
This has been merged. Thanks for your help!
