### ISSUE TITLE
Add access to startIndexWithBuffer/endIndexWithBuffer in IViewportIndices

### ISSUE THREAD

**Issue by AntonTrofimovich** [rintoj/ngx-virtual-scroller#248]
The problem with list items numbering.

Currently users have access only to indices which corresponding items are **visible** on the screen. But the number of **existing** elements is larger. So it's impossible to number list in the right way without “dirty” tricks.

**Comment by speige** [comment]
I agree with this. Feel free to code it up & submit a pull request. Thanks.

**Comment by speige** [comment]
Closing this. The PR you submitted for this issue has been merged. Please re-open if you think more changes need to be made. Thanks for your help!
