### ISSUE TITLE
Hiding scrollbar

### ISSUE THREAD

**Issue by al-matari** [rintoj/ngx-virtual-scroller#255]
Hallo everbody,

 i read in your docmention that is possible to hide the scrcollbar with
	   margin-right: -25px;
	   padding-right: 25px;
but it doesn't work for me.
Hier ist my css.
 ::ng-deep virtual-scroller.vertical {
    margin-right: -25px !important;
	   padding-right: 25px !important; 
  }

::ng-deep virtual-scroller.selfScroll.vertical {
    height: 75vh;
    margin-right: -25px !important;
    padding-right: 25px !important; 
  }

Is my code wrong?. Is there any way to doing it right?

Thank you
Matari

**Comment by speige** [comment]
This is really a CSS hack, but it does work in the all the browsers I've tested with. My guess is your css is not getting applied. Maybe you don't need ::ng-deep ?

![image](https://user-images.githubusercontent.com/2002030/46744671-d52d9700-cc68-11e8-8035-8286abe252e0.png)
Use developer tools to check if your style is being applied (or overridden by something else). You can also add it as an inline style directly from developer tools to prove the concept works.

This appears to be user error & it's really a CSS question, not a virtual-scroller specific question. So, I'm going to close this. If you continue to have issues you might try creating an example of your issue with stackblitz & asking for help with it on stackoverflow.
