### ISSUE TITLE
Scroll to index doesn't  work correctly with multiple columns

### ISSUE THREAD

**Issue by vegarda** [rintoj/ngx-virtual-scroller#258]
How to replicate: 
Change multiple columns demo from scroll to index 50 to 49.
See it doesn't scroll to the row with index 49.

How to fix:
in 
`calculatePadding`
change 
`let startingWrapGroupIndex = Math.ceil(arrayStartIndexWithBuffer / dimensions.itemsPerWrapGroup) || 0;`
to
`let startingWrapGroupIndex = Math.floor(arrayStartIndexWithBuffer / dimensions.itemsPerWrapGroup) || 0;`

**Comment by speige** [comment]
Thanks! This has been fixed & published to npm under version 1.0.11
