### ISSUE TITLE
[Question] How to detect current scroll position

### ISSUE THREAD

**Issue by tobiasmuecksch** [rintoj/ngx-virtual-scroller#261]
First of all - thank you for this amazing module!

I'm programming an app, that scrolls down to the bottom, when a new item arrives.
But I want the app to not scroll down, if the user has scrolled up more than 500px.

So my question is:
How can I read the current scroll position?

**Comment by speige** [comment]
Read the documentation at https://github.com/rintoj/ngx-virtual-scroller
The information you're requesting is there.

If you can't figure it out, let me know how you think the documentation could be improved.
If you find something not working, feel free to open a new issue.

Good luck with your app.

**Comment by speige** [comment]
Read the documentation at https://github.com/rintoj/ngx-virtual-scroller
The information you're requesting is there.

If you can't figure it out, let me know how you think the documentation
could be improved.
If you find something not working, feel free to open a new issue.

Good luck with your app.
