### ISSUE TITLE
[Question] How to detect scroll position

### ISSUE THREAD

**Issue by tobiasmuecksch** [rintoj/ngx-virtual-scroller#262]
First of all. **Thank you** for this amazing module!

I'm programming an app that scrolls down to the bottom, every time a new item is added to the array. But I don't wan't it to scroll down, if the user has scrolled up more than 500px.

My **Question** is:
How can I detect the current scroll position? I'm normally use to have a something like `scrollTop`:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop

**Comment by speige** [comment]
Read the documentation at https://github.com/rintoj/ngx-virtual-scroller
The information you're requesting is there.

If you can't figure it out, let me know how you think the documentation
could be improved.
If you find something not working, feel free to open a new issue.

Good luck with your app.
