### ISSUE TITLE
vertical + horizontal scroll?

### ISSUE THREAD

**Issue by schoening** [rintoj/ngx-virtual-scroller#275]
Hi, I have a huge table that goes both horizontal and vertical, is there a way to use both horizontal and vertical scrollbars at the same time?

**Comment by kykint** [comment]
you can try to put one scroller into another

**Comment by speige** [comment]
Unfortunately, this is not something we support. You'll have to figure this out on your own. Sorry :(

Closing this issue for now.

If you're able to figure something out that works, please re-open and add an explanation of how you got it working so future users can benefit. Thanks!
