### ISSUE TITLE
404 Not Found: @tweenjs/tween.js@^17.1.0

### ISSUE THREAD

**Issue by Lumlicious** [rintoj/ngx-virtual-scroller#283]
```
code E404
npm ERR! 404 Not Found: @tweenjs/tween.js@^17.1.0
```

Not sure if this repo is down or if the version is incorrect, but it's preventing installation.

Anybody else seeing this issue?

**Comment by speige** [comment]
Similar issues have been reported/resolved in the past. Usually without any code changes to ngx-virtual-scroller. Typically it involves adding extra dependencies to the consuming application's package.json file.

Please search the old closed issues to see if you can resolve this on your own. If you're unable to resolve this, please re-open.

Thanks.

**Comment by speige** [comment]
I've re-arranged the publish format to prepare for ivy support. In the process I believe I may have fixed the tween issue. Can you re-test with the latest version on npm 2.0.4 ?
