### ISSUE TITLE
[Help] Firestore example?

### ISSUE THREAD

**Issue by peavers** [rintoj/ngx-virtual-scroller#287]
Before I embrace down this painful path, thought I'd ask here. Does anyone have a recent example of implementing this awesome module with Firestore as the data provider?

**Comment by speige** [comment]
Sorry, you'll need to figure this out on your own. We don't have the resources to do this type of support. You could try StackOverflow. However, I honestly doubt it will be very hard. Read the documentation, it's very thorough.

After you've made an honest attempt & can't get it working, feel free to re-open this issue if you have an actual bug to report.

Good luck :)

**Comment by peavers** [comment]
For anyone that comes across this via Google or whatnot I managed to solve this. Warning I'm not a JavaScript guy so there is probably a much better way of doing things but this works. 

https://gist.github.com/peavers/0a6d3cd6104b017c0f8476cad5c43f4b
