### ISSUE TITLE
Discrete user experience between Mac and Windows after scrolling to top/ bottom of the list

### ISSUE THREAD

**Issue by wunaidage** [rintoj/ngx-virtual-scroller#289]
On Mac, using chrome or firefox, after scrolling to top/bottom of the list, if you keep scrolling, the parent element will start to move up/down.
On Windows, using chrome or firefox, after scrolling to top/bottom of the list, if you keep scrolling really quick, the parent element does not move, unless you stop for like half second and restart scrolling your mouse wheel, only then the parent element will move.

This happens in the demo page too.

**Comment by wunaidage** [comment]
I will. thanks for replying

**Comment by speige** [comment]
I was able to borrow a mac for a bit. I tested in chrome & didn't notice anything strange. I didn't test with safari/firefox. I think the video will help me understand, because I'm probably misunderstanding the issue.

**Comment by wunaidage** [comment]
[https://www.youtube.com/watch?v=GNyojIaA66Y](url) this is just for the Windows 10 + Chrome scenario. Mac works just fine.

**Comment by speige** [comment]
I think I understand what you're complaining about.

If there are 2 nested scrollbars on the page the mouse scrollwheel will only affect the scrollbar of the nearest parent to the current mouse position. This means if you scroll to the bottom of a virtual-scroller using the mousewheel & the window has an extra scrollbar, you cannot use the scrollwheel to scroll the page unless you move the mouse pointer out of the virtual-scroller element.

This is a known bug, however we don't know how to fix it. It seems to be default browser behavior that we don't know how to override.

I'll update the documentation to make this clear, so it's less confusing to future developers.

Sorry about that. If you have ideas on how to fix it, feel free to make an attempt & submit a pull request.

My suggestion would be to avoid nested scrollbars, if possible.
Good luck!

**Comment by wunaidage** [comment]
haha, thanks for replying. I see the same happens in angualr's cdk-virtual-scroll. Guessing it's a common bug.
