### ISSUE TITLE
Event that can be used to load data before hitting the end of the scroll list

### ISSUE THREAD

**Issue by skreel** [rintoj/ngx-virtual-scroller#292]
Is there something I can use besides vsEnd / event.end to call fetchmore() from? I would like to do infinite scroll but I would like to fetch the next chunk before reaching the end of the scroll. This way the user experience will be nicer in that it will fetch new data before hitting the end. The user will not have to wait for loading this way (unless they're scrolling super fast and make it to the end before the next chunk is loaded.)

**Comment by speige** [comment]
You can do this easily today. Read through the documentation & try to figure it out. If you get stuck, you can reopen with a more specific description of your problem.

These APIs will probably be helpful to look at:
vsUpdate, vsChange, viewPortInfo, viewPortItems

Good luck!
