### ISSUE TITLE
Tables fix header is not working in Angular 7

### ISSUE THREAD

**Issue by aryaroudi** [rintoj/ngx-virtual-scroller#293]
Hi, I have tried your sample code for `HTML Table` in an empty view and it just doesn't fix the header on top. Any particular reason that may cause this?

```
<virtual-scroller #scroll [items]="this.nodes">
  <table>
    <thead #header>
    <th>Index</th>
    <th>Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Address</th>
    </thead>
    <tbody #container>
    <tr *ngFor="let item of scroll.viewPortItems">
      <td>{{item.id}}</td>
      <td>{{item.name}}</td>
    </tr>
    </tbody>
  </table>
</virtual-scroller>
```

**Comment by speige** [comment]
This should be working. Would you mind creating a stackblitz that reproduces the issue?

**Comment by aryaroudi** [comment]
> This should be working. Would you mind creating a stackblitz that reproduces the issue?

I guess this could be because of the parent's `overflow scroll`. it is setting the height as the total height of the whole elements:

`<div _ngcontent-c1="" class="total-padding" style="height: 2267px;"></div>` 

how this heigh being calculated?

**Comment by speige** [comment]
Please go to this url
https://rintoj.github.io/ngx-virtual-scroller
and click "samples" and scroll down to the section "With Table".

Are the fixed headers working for you in that sample?
For me, the sample appears to be working fine.
If you agree, then it's probably something with your code.

If it's an issue with your code, I can't help troubleshoot without a stackblitz. Sorry :(

If you want to know how the height is calculated, feel free to read through the code & step through it with a debugger. It's too complex for me to explain :)

**Comment by aryaroudi** [comment]
Thanks @speige yes it should be somewhere in my styles. I will share the solution in case if happens to someone.

**Comment by kamal0912** [comment]
> Please go to this url
> https://rintoj.github.io/ngx-virtual-scroller
> and click "samples" and scroll down to the section "With Table".
> 
> Are the fixed headers working for you in that sample?
> For me, the sample appears to be working fine.
> If you agree, then it's probably something with your code.
> 
> If it's an issue with your code, I can't help troubleshoot without a stackblitz. Sorry :(
> 
> If you want to know how the height is calculated, feel free to read through the code & step through it with a debugger. It's too complex for me to explain :)

Hi @speige , Can you please share code for this table? In the demo above, its working fine but in my project I am having some issues. Thanks in advance. :)

**Comment by speige** [comment]
@aryaroudi I'm not sure how to fix the flickering. If you find a way to fix it please submit a pull-request. Thanks.

**Comment by speige** [comment]
@kamal0912 The code is all in github. Good Luck :)

**Comment by aryaroudi** [comment]
> @aryaroudi I'm not sure how to fix the flickering. If you find a way to fix it please submit a pull-request. Thanks.

Hey Speige, No, unfortunately. I'm using Angular Material VS now!
