### ISSUE TITLE
support rtl

### ISSUE THREAD

**Issue by abuassar** [rintoj/ngx-virtual-scroller#298]
thanks for this fine component,

but when I tried horizontal scrolling while in rtl mode, it simply didn't work

by setting `<html dir="rtl">` it shows white empty space.

please fix it so I can use it in my app

much appreciated

**Comment by speige** [comment]
Sorry, we don't have time to fix this. If you'd like to fix it, please do so & submit a pull request.

Thanks.

**Comment by ItaiYosephi** [comment]
Any updates on that?

**Comment by NoamBuzaglo** [comment]
#410
