### ISSUE TITLE
'window is not defined' in Angular Universal/SSR

### ISSUE THREAD

**Issue by blattersturm** [rintoj/ngx-virtual-scroller#306]
Using the component with Angular Universal seems to lead to an error [in the constructor](https://github.com/rintoj/ngx-virtual-scroller/blob/28be46d5014a97a484ddbebaf884e21ef04b5eae/src/virtual-scroller.ts#L143).

```
ERROR { Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at new VirtualScrollerComponent 
```

**Comment by phuchieuct93abc** [comment]
I got the same problem,  I can't find a solution until now. Hope this issue will be fixed in the next version.

**Comment by speige** [comment]
This is an issue with many libraries for SSR. The typical way to fix it is with something like this (in your main.server.ts)

```
	const domino = require('domino');
	const win = domino.createWindow(template);
	global['window'] = win;
```

If you google/stackOverflow you should be able to find more help.
