### ISSUE TITLE
Up and down buttons on keyboard do not keep scrolling the section in Demo

### ISSUE THREAD

**Issue by hassanasad** [rintoj/ngx-virtual-scroller#307]
On the DEMO page ( https://rintoj.github.io/ngx-virtual-scroller/samples ) pressing Up and Down buttons do not seem to work the way they are supposed to. Few elements scroll and then the page itself starts scrolling. Is it possible to fix this?

**Comment by speige** [comment]
This is a known issue. I'm not sure how to fix it. If you find a way to fix it, please submit a pull-request. Thanks!
