### ISSUE TITLE
Refresh()

### ISSUE THREAD

**Issue by web-felicons** [rintoj/ngx-virtual-scroller#308]
Please keep the Refresh() method available in the next version. It solves the problem for us with ease.

**Comment by georgegrafos** [comment]
Same, I needed it to update the elements in the virtual scroller when they were re-ordered from another part of the page.

**Comment by subkkonen** [comment]
+1
It's a great tool, keep it please!

**Comment by shmunj** [comment]
+1
Same here.

**Comment by softwareCobbler** [comment]
It appears to be present on `VirtualScrollComponent`'s prototype, as `refresh`.  

Grab a reference in your component with `@ViewChild(<your template ref here>) XYZ` and you can call refresh on it, easy as `XYZ.refresh()`.  

Works on my machine anyway, w/ ngx-virtual-scroller 1.0.16.

**Comment by casper5822** [comment]
Also for us. Refresh() method is import and fix some component problems. Keep it please.

**Comment by softwareCobbler** [comment]
+1

**Comment by hristina123** [comment]
+1, great tool, keep it !

**Comment by SchnitzelAndSpaetzle** [comment]
+1
