### ISSUE TITLE
how to get index of scrolltoindex scrolled item

### ISSUE THREAD

**Issue by emko** [rintoj/ngx-virtual-scroller#309]
I am struggling with this problem, how can i get the index of the item scrolltoindex scroll to so that i can target it to add a css class.

thanks

**Comment by amineamami** [comment]
one way is to add itemSelected event when you click on one of the items, save it's index in a variable then use it to scroll to your specific item

**Comment by speige** [comment]
Issues are for reporting bugs, not for Questions. Read through the documentation. If you're still confused, read through the source code or submit a question on StackOverflow. Sorry, we don't have the time/resources to help you research.
