### ISSUE TITLE
ngx-virtual-scroller with filter

### ISSUE THREAD

**Issue by indraraj26** [rintoj/ngx-virtual-scroller#311]
if you type so fast in searchbar and erase everthing do it for 1-2 times your application will get hanged.

````
 <virtual-scroller #scroll [items]="countryList | filterBy: countryListFilter" bufferAmount="10">
          <button ion-item no-lines class="vir-button" *ngFor="let con of scroll.viewPortItems" (tap)="uSelected(con)">
            <span class="user-name capitalize">{{con.name}}</span>
        </button>
        <button ion-item *ngIf="(countryList | filterBy: countryListFilter).length === 0">
                <span class="user-name capitalize">No data found</span>
        </button>
    </virtual-scroller>
````
ionic 3.9.2
angular 5.2.10

**Comment by gesielrosa** [comment]
Same issue!
I using with ionic, and on Android is ok, but on iOS the screen take blank.

**Comment by indraraj26** [comment]
but my application gets hanged i remembered because of this issue reference issue #304  i made the changed to tsconfig

**Comment by ahmadmu** [comment]
May I ask why you need this library for  in Ionic? Doesn't Ionic already provide its own virtual scrolling directive? (collection-repeat?)

**Comment by gesielrosa** [comment]
Have differences. This ngx-scroller is better in most aspects. But in iOS, on keyboard hide, the content size has changed and the scroll not rendered correctly.
ionic-vscroll only works inside the specific tag (ion-content), since ngx works in any html tag.

I solved the problem with the virtual-scroll and infinite-scroll of the ionic itself.

The ionic-vscroll problem was rendering with a list of more than 4,000 elements with images. It takes too long to render.

Sorry for my bad English.

**Comment by speige** [comment]
Please create a stackblitz which reproduces the bug to make it easier to debug this issue. Thank you.

**Comment by indraraj26** [comment]
@ahmadmu This is the reason that we need this package
Link : https://github.com/ionic-team/ionic-v3/issues/986

**Comment by wartab** [comment]
That issue rather sounds like an issue with the filterBy pipe you are using. Checking their issues in Github several other people suffer from performance issues or hanging of the application without the use of ngx-virtual-scroller. 
That pipe does trigger by change detection. If you have many elements, it will often iterate over them when there's no reason to do so. I recommend applying the filters yourself.
