### ISSUE TITLE
[Question] Is there a way to use this repo with immutable.js?

### ISSUE THREAD

**Issue by adarowiec** [rintoj/ngx-virtual-scroller#312]
Following title: I was wondering if the author knows - is there a way for me to provide immutable.js List into [items] input and successfully iterate over?
-------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/26795400/53880348-0f7d4380-4011-11e9-9d09-acdfa5cd8895.png)

-------------------------------------------------------------------------------
Concept of what I'm trynna do:

![image](https://user-images.githubusercontent.com/26795400/53880634-c24da180-4011-11e9-9a6d-c6a8f5b6fbfe.png)

--------------------------------------------------------------------------------

**Comment by speige** [comment]
Issues are for reporting bugs, not for Questions. Sorry, we don't have the time/resources to help you research. You could try StackOverflow.
