### ISSUE TITLE
Suggestion on dynamic child-item height

### ISSUE THREAD

**Issue by davidvalen95** [rintoj/ngx-virtual-scroller#314]
firstly thankyou for usefull plugin.

i have read through your issue and currently `virtual-scrol` still unable to `predict` `child-height` dynamically  until its `fully rendered`, causing the jumping window experience to the user. 

sorry that i cannot fork child to this repo and do the code

i have got an idea. Actually we can render `previous-item-buffer` and `after-item-buffer` with `visibility:hidden` or `position:absolute;left:9999999;` this will give you the predicition of upcoming child height wether you are scrolling up or down. then problem solved for "until its fully rendered" issue

please, if this really can make, this will be awesome, because virtual scrolling suppose able to have dynamic child height

thankyou

**Comment by speige** [comment]
If you think this solution could work, please code it up & submit a pull request. Thanks.

**Comment by Juanperezc** [comment]
I have the same problem with dynamic child-item (chat app)
