### ISSUE TITLE
How to efficiently add and remove elements from the model?

### ISSUE THREAD

**Issue by lamba92** [rintoj/ngx-virtual-scroller#317]
If I update all `[items]` the component will redrawn its elements. For example, how can I notify the `virtual-scroller` that an item may have been inserted outside the current shown ones and thus no redraw is actually needed? For reference, have a look at [Android's RecyclerView](https://developer.android.com/guide/topics/ui/layout/recyclerview), especially have a look at the [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter)'s methods which names start with `notify`.

**Comment by speige** [comment]
This is not currently a supported feature in the library. In most cases it shouldn't cause a noticeable performance issue. If it's causing a major issue for you, you might change how you're modifying the array. If you think it's a bug in the library, please re-open with a StackBlitz that reproduces the issue.

If this is a feature you think would be useful, you could consider submitting a pull-request.
