### ISSUE TITLE
latest version 2.0.7 depends on angular 6

### ISSUE THREAD

**Issue by abuassar** [rintoj/ngx-virtual-scroller#324]
in the readme it is written that this component supports angular 4+, hence I'm using it in an angular5 app.

but now I'm using an older version as the current one has peer dependency on angular 6.

**Comment by speige** [comment]
The readme no longer states that we support 4+.

The latest version of ngx-virtual-scroller supports the latest version of Angular. If you don't want to upgrade your app to the latest angular, you'll need to leave ngx-virtual-scroller on an older version as well.
