### ISSUE TITLE
Feature: support scroll snap

### ISSUE THREAD

**Issue by abuassar** [rintoj/ngx-virtual-scroller#326]
I'm using ngx-virtual-scroller to display pages in a book-like app,

I'd like the user to scroll through pages but when he finish scrolling; a page is snapped to its start position instead of being displayed half way.

in css there is [scroll-snap](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type) but it didn't work maybe because the component uses translate instead of normal scrolling

I also found another component [ngx-virtual-swiper](https://github.com/vasyliv/ngx-virtual-swiper) but it works only with CDK virtual scroller.

any hints are appreciated.

**Comment by speige** [comment]
This is not currently a supported feature. I don't have any suggestions on how to do it, sorry :(

If you decide to code this feature, feel free to submit a pull request. Thanks.
