### ISSUE TITLE
Breaking change introduced in minor version

### ISSUE THREAD

**Issue by wartab** [rintoj/ngx-virtual-scroller#328]
After updating the minor version of ngx-virtual-scroller from 2.1.0 to 2.2.0, a feature has been removed and therefore introduces a breaking change. 
Please remove this release from NPM and publish it with by bumping the version with major version upgrade, as this breaks automated builds relying on [semver](https://semver.org/) rules.
Also, it would be nice if using deprecated features resulted in a warning when being used before they are being removed entirely.

See the guidelines for NPM packages on semantic versioning: https://docs.npmjs.com/about-semantic-versioning

**Comment by kykint** [comment]
@speige - It's true - let's remove 2.2.0 and introduce 3.0.0

**Comment by speige** [comment]
I've made the changes you requested. Sorry, I should follow semver better.

No features were removed, only renamed. I figured it would only take 5-seconds to fix breaking change, so I didn't think it was necessary to update the major version. Sorry for my mistake.

Warning was given in the ReadMe for a LONG time before removing. However, the ReadMe is large & it's unlikely all users will read it thoroughly. Is there a way to have the Angular compiler warn when using deprecated features? I should research this.

**Comment by wartab** [comment]
Thanks a lot for the very quick reaction :)

There's no real way to do it in an "angular-way" (or at least I'm not aware of one), but in this specific case, I would have simply replaced the raw variable classes like `start` or `end` by [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) & [setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) and used console.warn() whenever these are invoked.
