### ISSUE TITLE
Reducing the items array length to less than available viewport cuause issues

### ISSUE THREAD

**Issue by ggehlot1980** [rintoj/ngx-virtual-scroller#330]
I have created the items array with a certain size which is more than what the viewport can accomodate. Then I go and remove few elements form the items array such that whole of the items can now fit into the viewport. Now if I again increase the size of the items array to the initial size, the viewport doesn't increse in height to encompass the whole avaiable height. The scollbar height never changes in all these steps which means the height of the virtual scroll component has not changed but just the viewport size is changing and it doesn't increase back to the original size if the items arrary size increase back to normal and I have to scroll unnecessarily more to see the last item in the list as the avaialble viewport has reduced.

**Comment by speige** [comment]
Please create a StackBlitz to help diagnose this problem. Thanks.

**Comment by ggehlot1980** [comment]
I could overcome the problem by doing - this.virtualScroller.viewPortItems = null, before changing the items array being referred by the virtualScroller. If I don't do this the viewport some how doesn't expand to accomodate the increated lenght of the items array. So if you want you can close this issue.
But I am seeing one exception within the library 
Uncaught TypeError: Cannot read property '0' of null
    at refreshCompletedCallback (ngx-virtual-scroller.js:491)
    at ngx-virtual-scroller.js:588
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:2281)

Below is the fucntion refresh_internal, in which the exection is coming. The last line of the code mentioned below - 'var oldStartItem_1 = oldViewPortItems_1[0];' is throwing the exception.

VirtualScrollerComponent.prototype.refresh_internal = function (itemsArrayModified, refreshCompletedCallback, maxRunTimes) {
        //note: maxRunTimes is to force it to keep recalculating if the previous iteration caused a re-render (different sliced items in viewport or scrollPosition changed).
        //The default of 2x max will probably be accurate enough without causing too large a performance bottleneck
        //The code would typically quit out on the 2nd iteration anyways. The main time it'd think more than 2 runs would be necessary would be for vastly different sized child items or if this is the 1st time the items array was initialized.
        //Without maxRunTimes, If the user is actively scrolling this code would become an infinite loop until they stopped scrolling. This would be okay, except each scroll event would start an additional infinte loop. We want to short-circuit it to prevent this.
        var _this_1 = this;
        if (refreshCompletedCallback === void 0) { refreshCompletedCallback = undefined; }
        if (maxRunTimes === void 0) { maxRunTimes = 2; }
        if (itemsArrayModified) {
            //if items were prepended, scroll forward to keep same items visible
            var oldViewPort_1 = this.previousViewPort;
            var oldViewPortItems_1 = this.viewPortItems;
            var oldRefreshCompletedCallback_1 = refreshCompletedCallback;
            refreshCompletedCallback = function () {
                var scrollLengthDelta = _this_1.previousViewPort.scrollLength - oldViewPort_1.scrollLength;
                if (scrollLengthDelta > 0 && _this_1.viewPortItems) {
                    var oldStartItem_1 = oldViewPortItems_1[0];

**Comment by speige** [comment]
I'm sorry, I can't help you unless you provide a StackBlitz.
