### ISSUE TITLE
[question] catch end of rendering

### ISSUE THREAD

**Issue by eLeontev** [rintoj/ngx-virtual-scroller#333]
Hi,

 I did not see any related questions, so I ask it here:)
I'm not so familiar to angular ecosystem, so my question is next: Do we have any event which will be fired once all the items in ngxVirtualScroller will be rendered (particular case: determinate that a page is rendered and I can hide the loader)?

**Comment by speige** [comment]
Try the vsUpdate event from the ngx-virtual-scroller api. It will happen every time rendered items are changed, so if you're using it to hide a spinner/loading icon you only need the event 1x & can ignore it afterwards.
