### ISSUE TITLE
Is it possible to cache\hide from DOM components instead of destructuring? 

### ISSUE THREAD

**Issue by deser** [rintoj/ngx-virtual-scroller#335]
Related to #296 
So is it possible to use instead of ngIf something like ngStyle or don't remove components at all once they are rendered?

**Comment by kykint** [comment]
You can just not use virtual scroll - and youк components won't be destroyed. The idea of virtusl scroll is to remove a lot of nodes from DOM and free the memory they used.

**Comment by deser** [comment]
Yeah, I understand. The problem is that I need fast first rendering in other words when my right view (slide panel) is opened I need to render only visible items there. My components are tough so virtual scrolling plays bad when starting to stroll up and down.

**Comment by speige** [comment]
Closing. Sorry, this is not a feature we're going to implement.

Virtual-Scroller is extremely performant, if your rendering is slow while scrolling you need to fix your custom components. There is an entire section in the readme about how to improve scrolling performance.

As stated in #296 if you have any external data being loaded with each component, you should cache that in your own custom code.
