### ISSUE TITLE
[Question] Intitial scroll index/position

### ISSUE THREAD

**Issue by btxtiger** [rintoj/ngx-virtual-scroller#341]
How can I define the initial scroll position / item index? Is there a proper way to pass it to the component, instead of scrolling to y position after init? This always causes a visible scroll animation.

I found `IPageInfo.scrollStartPosition`, but I could not find out how it is usable.

**Comment by speige** [comment]
IPageInfo is readonly. You'll have to use scrollToIndex or scrollToPosition. There is a parameter animationMilliseconds which you can set to 0 to make the scrolling instant.

There may still be a small amount of flicker between the 1st render & the time you call scrollToPosition. You may be able to reduce this by calling the method immediately after initializing the items array. If you're not able to completely remove the flicker, feel free to code something up & submit a pull request.

Good Luck!

Please re-open if you're unable to get it working after making an honest attempt. Thanks.

**Comment by btxtiger** [comment]
Thank you!
