### ISSUE TITLE
multiple-column cards  are invisible until resize container height (only the first is displayed at the beginning)

### ISSUE THREAD

**Issue by casper5822** [rintoj/ngx-virtual-scroller#344]
I have problems with horizontal cards. I tried both bootstrap column and your list-item. 
This is my use case:

- 2 elements 
- bufferAmount is not set
- window is sized with a small height, just a portion of the top of the card is visible;

In this situation, at the beginning, only the first card is displayed, then only if i make the window height bigger, so i increase the height of the page, the second card magically appear.

This problem is not present if i set a bufferAmount (but bufferAmount has poor performance in my case) or if the page is in full height.

I don't understand why only the first is rendered and how to fix this problem.

Thank you for any suggestion.

This is my case with some snapshot:
In the first picture, there is only the first card, then i increase the page height just a little moving the chrome inspector down and at a certain height the second card is displayed

![first-card](https://user-images.githubusercontent.com/26361006/59661676-9793ed00-91ab-11e9-8eb4-a52e6b019dd8.png)

![second-card](https://user-images.githubusercontent.com/26361006/59661684-9cf13780-91ab-11e9-90f8-f8fb7e5ea5e2.png)

**Comment by casper5822** [comment]
I solve the issue.
The problem was with padding on my cards. For some reason it creates problem on height calculation.

Thank you in every case.

**Comment by casper5822** [comment]
This problem is not solved. Sorry.
I'm making tests to understand better the issue.
If i set the scroll.window parentScroll, the problem occurs, if i set a container with fixed height, it works.
I'm using bootstrap in this moment and it's like virtual-scroller doesn't calculate the right scrollHeight because there where multi columns. 
I tried some similar issues about bootstrap, template-rows etc. 
I also tried the list-item for multiple-column demo but not works.

Thank you in advance.

**Comment by speige** [comment]
@casper5822 I need a stackblitz before I can help :)

**Comment by speige** [comment]
Oh, It looks like this is similar to the other issue you posted in & bufferAmount is a viable workaround.
How noticeable is the performance impact? Unless you're setting it to a very large value, the impact should be minimal. My suggestion would be to use bufferAmount & then follow all the performance guidelines in the readme.

**Comment by casper5822** [comment]
The open multi column issue is this same issue so i will close it.
We made other tests and we find the same problem (math round). 
We also tried the bufferAmount solution but it is not a valid workaround because with hundreds of cards very slow rendering occurs and our performance tests are not passed. In some case, with complex cards a user back to previous page takes up to 8 seconds. 
So we have at this point only one solution redesign our cards in a vertical list waiting for a bug fix in the future. 
Thank you for all @speige

**Comment by speige** [comment]
Ok. I strongly suggest going over all the performance documentation at https://github.com/rintoj/ngx-virtual-scroller

Search for headings starting with "Performance - "

If you follow those guidelines, I think the performance issues will be improved. A small bufferAmount shouldn't cause such a negative performance impact. If you're following those guidelines & still have performance issues with bufferAmount, I'd be interested in investigating further.

**Comment by casper5822** [comment]
Ok i will reopen the issue. Tomorrow i will follow the guidelines and stop the new  layout design. 
Thank you for all.

**Comment by casper5822** [comment]
Sorry another report about this problem that we notice in one test is the follow:
It seems like this problem occurs if the container viewport height has a height less than the card  (child) item. So in this case, the others card are considered out of the vertical viewport.
Maybe, the fact is that in a multi column situation the viewport witdh must be considered and not only the height.

**Comment by speige** [comment]
@casper5822 In this situation is bufferAmount still a valid workaround (ignoring the performance impact)?

**Comment by casper5822** [comment]
Yes the bufferAmount is a valid workaround because scroller bypass the viewport,  in fact it was the first fix we made, but we stack at performance tests.

**Comment by casper5822** [comment]
We adopted the bufferAmount workaround at the end.
The performances were improved.
In our case the problem was a "star rank directive" for angular 2 inside the card:
It seems to be heavy to render so we implemented a custom ranking stars system.

Now with a bufferAmount = 3 we have about 0.8 - 1.5 seconds on a "go back page" call on a 2000 items . The delay is due to the scrollToIndex usage in order  to restore the same scrollPosition in the list.

It is acceptable for now.
Thank you @speige

**Comment by EduardRakov** [comment]
I had a similar problem - be sure that your item-block is NOT wrapped to any other blocks (e.g. div), example:

**Incorrect**

```
 <virtual-scroller #scroll
                      [items]="items"
                      [parentScroll]="scroll.window"
                      (vsChange)="loadMore($event)"
                      [scrollThrottlingTime]="150">
                <div> <!-- this block will break the scroller -->
                    <div class="card col-md-3 no-gutters mt-1" *ngFor="let item of scroll.viewPortItems">
                        ...
                    </div>
                </div>
    </virtual-scroller>
```

**Correct**
```
 <virtual-scroller #scroll
                      [items]="items"
                      [parentScroll]="scroll.window"
                      (vsChange)="loadMore($event)"
                      [scrollThrottlingTime]="150">
                <div class="card col-md-3 no-gutters mt-1" *ngFor="let item of scroll.viewPortItems">
                     ...
                </div>
    </virtual-scroller>
```

**Comment by casper5822** [comment]
Thank you. I have not any div between. The problem is how the scroller works. For now the solution for me is set bufferAmount e quale to the number of card in a row

**Comment by EduardRakov** [comment]
@casper5822 I use 4 items per row without any `flex` and everything is fine (you have to set height of `html` and `body` as well (for me it's `100%`)) and `bufferAmount` is not used in my case.
Also you may try to use the following workaround - set scrollerHeight manually. (in one of my case it helped for me using ` [scrollbarHeight]="itemHeight"`, I know looks like a dirty trick but works.

**Comment by EduardRakov** [comment]
@casper5822 also if your page is dynamically changed - try to `invalidateAllCachedMeasurements`

**Comment by edvenkat** [comment]
@casper5822  how to use that give me the example
