### ISSUE TITLE
Virtual scroll start on bottom

### ISSUE THREAD

**Issue by cube27rus** [rintoj/ngx-virtual-scroller#366]
Hi. 
Are there any ways to scroll from bottom to top like a chat?
I had an idea - using scrollInto last element after data init, but I need track scroll event only if the user scroll manually.

**Comment by cube27rus** [comment]
Done using animationCompletedCallback

**Comment by sharbel93** [comment]
where is it applied?

**Comment by cube27rus** [comment]
> 
> 
> where is it applied?
> the animationCompletedCallback?

Call scrollToPosition after view init and the last argument is animationCompletedCallback

**Comment by dudipsh** [comment]
@bond-igor 
Whats the best way, if possible to implement a virtual scroll that populates from the bottom, and when scrolling up brings another item in (like pagination)


![Image description](https://a.slack-edge.com/4bc9d/img/api/articles/blueprints/approval_workflows_animated.gif)
