### ISSUE TITLE
Max items count in viewport depend on item height 

### ISSUE THREAD

**Issue by Khokhlachov** [rintoj/ngx-virtual-scroller#399]
First of all thanks for making this library it is great.

If use big list with >= than 10 000 000 items and set one item height more than 30px control stop working correctly 
Ex:  
-10 000 000 items 40px per item last rendered item is #838860
-10 000 000 items 60px per item last rendered item is #559240

[example playground](https://stackblitz.com/edit/infinity-virtual-scroll-max-items-count)

**Comment by speige** [comment]
Can you try again with the latest version of the library? I believe this issue has been fixed. Please re-open if you continue to have errors.
