### ISSUE TITLE
Unable to select text inside virtual scroller

### ISSUE THREAD

**Issue by xpagliosa** [rintoj/ngx-virtual-scroller#407]
I have a chat window with the virtual scroller inside. I cannot select any text within the virtual scroller. How can I solve this?

**Comment by speige** [comment]
It works fine on https://rintoj.github.io/ngx-virtual-scroller/samples
That means it's probably an issue with your code, not ngx-virtual-scroller.

Closing. If you're able to prove that it's ngx-virtual-scroller, please re-open.
