### ISSUE TITLE
App freezes 

### ISSUE THREAD

**Issue by shubh48** [rintoj/ngx-virtual-scroller#411]
Angular App freezes if left unused for about an hour this is because of ngx-virtual scroll.
If disables it works fine.

**Comment by speige** [comment]
Please create a stackblitz reproducing the problem. Or, show how it can be reproduced using https://rintoj.github.io/ngx-virtual-scroller/samples

I can't troubleshoot without a way to reproduce it.

Please re-open when you have reproduction instructions.
