### ISSUE TITLE
Other scroll-handling directives stopped to work with angular 9

### ISSUE THREAD

**Issue by Diogen84** [rintoj/ngx-virtual-scroller#412]
```html
<virtual-scroller
    (click)="outputScroll(scroll)"
      #scroll
      [parentScroll]="scroller.window"
      [modifyOverflowStyleOfParentScroll]="false"
      [bufferAmount]="15"
      [items]="rendredRows$ | async"
    >
      <app-row *ngFor="let row of scroller.viewPortItems; trackBy: trackByUniqID">
...
      </app-row>
</virtual-scroller>
```

In angular 7 it is working perfect. Nevertheless, after migration to angular 9 the window-scroll related directives stopped to get the scroll event detection. When the virtual-scroll tag is not present in the code they are working fine. Seems it is a kind of conflict on the ViewChild of the #scroll

**Comment by whyboris** [comment]
I'm unsure if it's helpful, but I upgraded to _Angular 9_ in the app and updated _ngx-virtual-scroller_ to the latest version and got it all to work in my app, no hiccup 🤷‍♂ 

https://github.com/whyboris/Video-Hub-App/blob/master/src/app/components/home.component.html#L1014

```html
    <virtual-scroller
      #scroll
      ...
    >
      <app-gallery-item *ngFor="let item of scroll.viewPortItems">
...
      </app-gallery-item>
    </virtual-scroller>    
```
