### ISSUE TITLE
scrollToPosition can not handle 0ms

### ISSUE THREAD

**Issue by whyboris** [rintoj/ngx-virtual-scroller#420]
The method as it's written can not handle `0` as the number of milliseconds: 

https://github.com/rintoj/ngx-virtual-scroller/blob/d4732774283a9f736fbdef13e5cb46adf1050208/src/virtual-scroller.ts#L537

https://github.com/rintoj/ngx-virtual-scroller/blob/d4732774283a9f736fbdef13e5cb46adf1050208/src/virtual-scroller.ts#L548

When using the method `scrollToPosition(1000, 0)` the method uses the default animation length rather than 0ms because the check is:

```
  if (!animationMilliseconds) {
```

I'm happy to create a PR 😎

**Comment by whyboris** [comment]
🤔 I'm unsure what's happening any more 😕 
Yesterday I was getting the behavior that if I set the second argument to `0` the scroller would animate the scrolling, but today I can't seem to replicate the problem.

So it seems that the `if(!animationMilliseconds)` is defined specifically to catch the scenario `if(animationMilliseconds === 0)` 🤷‍♂ 

I'll look some more 😅

**Comment by speige** [comment]
Sounds like it's working as intended, since you're no longer able to reproduce. Also, looking at the code it seems correct to me. Please re-open if you're able to reproduce the issue again.
