### ISSUE TITLE
cannot hide address bar when scroll down in Android Chrome

### ISSUE THREAD

**Issue by dmc31a42** [rintoj/ngx-virtual-scroller#436]
How to hide address bar when scroll down like 'parent scroll sample' of https://rintoj.github.io/ngx-virtual-scroller or https://material.angular.io/components/sidenav/overview#creating-a-responsive-layout-for-mobile-amp-desktop example (https://stackblitz.com/angular/onaqmlvynqd)
I'm using mat-sidenav.

Source code:
https://nakwonelec.visualstudio.com/TwitchClipSearch/_git/TwitchClipSearch?path=%2F&version=GBngx-virtual-scroll&_a=contents f801b71b239018247963139fe2b5a24fceeadd22  commit in ngx-virtual-scroll branch

**Comment by HybridShivam** [comment]
**Use scrollbar of window**
_If you want to use the window's scrollbar, set parentScroll._

> <virtual-scroller #scroll [items]="items" [parentScroll]="scroll.window">
>     <input type="search">
>     <div #container>
>         <my-custom-component *ngFor="let item of scroll.viewPortItems">
>         </my-custom-component>
>     </div>
> </virtual-scroller>

**Comment by HybridShivam** [comment]
This will do it : )

**Comment by dmc31a42** [comment]
@HybridShivam Thnaks. I confused problem of sidenav.
In sidenav, due to overflow, virtual-scroller does not work. so, i try to attach parentScroll to external div.

just for memo I write below

# How to use mat-sidenav and virtual-scroller together

1. make 'overflow' of mat-sidenav-container and mat-sidenav-content to 'visible' to fix virtual-scroller does not work in sidenav
```css
mat-sidenav-container {
  overflow: visible;
}
mat-sidenav-content {
  overflow: visible;
}
```
2. use scroll.window to work url hide
