### ISSUE TITLE
What in case for example 1 million records

### ISSUE THREAD

**Issue by ignaszewski** [rintoj/ngx-virtual-scroller#68]
In case we have 1000000 records (each row 30px) ?? totall div height will be 30 000 000 px.

In Chrome and Safari will be ok, but in IE and FF there is height limit for container (IE 1533917px FF17895696).

**Comment by mleibman** [comment]
I've hit this browser limitation when working on SlickGrid 7 years ago.  Some things never change :)
See https://stackoverflow.com/questions/2402953/javascript-data-grid-for-millions-of-rows/2569488#2569488 for one possible way of solving it.

**Comment by rintoj** [comment]
@ignaszewski, thanks for opening the issue. Moving this to low priority for now. I don't want to break already complex core logic. However I will consider this as I write the new version the component.

**Comment by ankuradhey** [comment]
@ignaszewski  What about 100000 records (each row 40px)?

**Comment by ignaszewski** [comment]
@ankuradhey as long as records * px <= IE Limit (1533917px) it will be no problem. Funny because during 1 month I step onto the same problem in 2 projects :).

**Comment by manju-reddys** [comment]
@mleibman I have implemented your brilliant idea (7year old but still rock solid 💯 ) see the [plnkr](https://plnkr.co/edit/K0SSAxlLOfukNVAIcd3t?p=preview). I have stuck with one problem, how can I navigate to an item? My attempt didn't work.

**Comment by speige** [comment]
@mleibman @manju-reddys  Please submit a pull request if your attempts were successful & I'll happily merge it. Thanks.

**Comment by MBcom** [comment]
@rintoj @speige i implemented a version using tranform translate X/Y for this issue. They are not limited and working even for millions of records. See #395

**Comment by speige** [comment]
This should be fixed by https://github.com/rintoj/ngx-virtual-scroller/pull/395 which has been merged & published to npm as version 4.0.3

Closing. Please re-open if it's not resolved.
